<%--<script type="text/javascript" src="<%=basePath%>/resource/frame/js/jquery-1.10.2.min.js" ></script>--%>
<script type="text/javascript" src="<%=basePath%>/resource/frame/js/jquery-3.2.1.min.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/jqueryui_1_5_2/jquery.easyui.min.js" ></script>
<%--<script type="text/javascript" src="<%=basePath%>/resource/frame/js/jquery-ui-1.9.2.custom.min.js" ></script>--%>
<script type="text/javascript" src="<%=basePath%>/resource/frame/js/jquery-migrate-1.2.1.min.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/frame/js/bootstrap.min.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/frame/js/bootstrap-inputmask/bootstrap-inputmask.min.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/frame/js/modernizr.min.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/frame/js/jquery.nicescroll.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/frame/js/scripts.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/bootalert/js/bootstrap-dialog.min.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/ztree/js/jquery.ztree.core.min.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/ztree/js/jquery.ztree.excheck.min.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/ztree/js/jquery.ztree.exedit.min.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/frame/frame.js" ></script>
<%--cript type="text/javascript" src="<%=basePath%>/resource/frame/js/iCheck/jquery.icheck.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/frame/js/icheck-init.js" ></script>--%>
<script type="text/javascript" src="<%=basePath%>/resource/frame/form/jquery.form.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/jqueryValidation_1_17/jquery.validate.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/jqueryValidation_1_17/additional-methods.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/My97DatePicker/WdatePicker.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/bus/common.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/validate/jqueryValidationCustMethod.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/chart/echarts.min.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/frame/js/jquery.stepy.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/validate/specValidate.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/lodop/LodopFuncs.js" ></script>
<script type="text/javascript" src="<%=basePath%>/resource/mloading/jquery.mloading.js" ></script>
<%--
<script type="text/javascript" src="<%=basePath%>/resource/frame/js/bootstrap-combobox.js" ></script>--%>
